repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-json
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [--autofix, --no-sort-keys]
    - id: check-yaml
    - id: end-of-file-fixer
      exclude_types:
        - diff
    - id: trailing-whitespace

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        args: [--max-line-length=120]
